[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Vincent Liao <vincent.liao@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
rust-crypto = "^0.2"